// <auto-generated />
using System;
using DistSysAcwServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistSysAcwServer.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20240413195327_Log")]
    partial class Log
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DistSysAcwServer.Models.Log", b =>
                {
                    b.Property<int>("logID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logID"), 1L, 1);

                    b.Property<string>("UserApiKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("logDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("logString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("logID");

                    b.HasIndex("UserApiKey");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.User", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.Log", b =>
                {
                    b.HasOne("DistSysAcwServer.Models.User", null)
                        .WithMany("logs")
                        .HasForeignKey("UserApiKey");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.User", b =>
                {
                    b.Navigation("logs");
                });
#pragma warning restore 612, 618
        }
    }
}
